- hosts: voiptest1
  tasks:
  - name: Include variables.
    include_vars: "main.yml"

  - name: Setup OpenSIPS repository key from keyserver (Debian)
    apt_key:
      keyserver: '{{ opensips_apt_key_server }}'
      id: '{{ opensips_apt_key_id }}'
    register: apt_key_result
    until: apt_key_result is success
    retries: 10
    delay: 2

  - name: Setup OpenSIPS repository (Debian)
    apt_repository:
      repo: 'deb {{ opensips_apt_repo }} {{ ansible_distribution_release }} {{ opensips_version }}-{{ opensips_build }}'
      state: present
      filename: opensips

  - name: Install OpenSIPS
    apt:
      update_cache: yes
      name: opensips
      state: present
    register: apt_install_result
    until: apt_install_result is success
    retries: 10
    delay: 2

  - name: Install OpenSIPS additional modules (Debian)
    apt:
      name: '{{ opensips_modules }}'
      state: present
    when: opensips_modules is defined and opensips_modules | length
    register: apt_modules_install_result
    until: apt_modules_install_result is success
    retries: 10
    delay: 2

  - name: Deploy OpenSIPS config
    template:
      src: '{{ opensips_config }}'
      dest: '/etc/opensips/opensips.cfg'
      mode: 0644
    when: opensips_config is defined
